/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(1)
	var __weex_style__ = __webpack_require__(2)
	var __weex_script__ = __webpack_require__(3)

	__weex_define__('@weex-component/ec2f855dde2db1d30ee1c5b8d3d760c7', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})

	__weex_bootstrap__('@weex-component/ec2f855dde2db1d30ee1c5b8d3d760c7',undefined,undefined)

/***/ },
/* 1 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "container",
	  "children": [
	    {
	      "type": "image",
	      "classList": [
	        "bgImg"
	      ],
	      "attr": {
	        "src": function () {return this.bgImgSrc}
	      }
	    },
	    {
	      "type": "text",
	      "classList": [
	        "gameName"
	      ],
	      "attr": {
	        "value": "行酒令"
	      }
	    },
	    {
	      "type": "div",
	      "classList": [
	        "startPlay"
	      ],
	      "children": [
	        {
	          "type": "a",
	          "classList": [
	            "startPlayA"
	          ],
	          "attr": {
	            "href": "https://13111211.github.io/weexCompetition/jsFile/selectNum.js"
	          },
	          "children": [
	            {
	              "type": "text",
	              "classList": [
	                "startPlayText"
	              ],
	              "attr": {
	                "value": "开始游戏"
	              }
	            }
	          ]
	        }
	      ]
	    },
	    {
	      "type": "div",
	      "classList": [
	        "quitPlay"
	      ],
	      "children": [
	        {
	          "type": "a",
	          "classList": [
	            "quitPlayA"
	          ],
	          "children": [
	            {
	              "type": "text",
	              "classList": [
	                "quitPlayText"
	              ],
	              "attr": {
	                "value": "退出游戏"
	              }
	            }
	          ]
	        }
	      ]
	    }
	  ]
	}

/***/ },
/* 2 */
/***/ function(module, exports) {

	module.exports = {
	  "bgImg": {
	    "width": 750,
	    "height": 1175
	  },
	  "gameName": {
	    "position": "absolute",
	    "top": 30,
	    "right": 30,
	    "color": "#FFFF00",
	    "fontSize": 110,
	    "fontWeight": "bold"
	  },
	  "startPlay": {
	    "width": 250,
	    "height": 80,
	    "position": "absolute",
	    "backgroundColor": "#0000FF",
	    "top": 590,
	    "left": 50
	  },
	  "startPlayText": {
	    "color": "#FFFFFF",
	    "fontSize": 60,
	    "textAlign": "center",
	    "fontWeight": "bold"
	  },
	  "quitPlay": {
	    "width": 250,
	    "height": 80,
	    "position": "absolute",
	    "backgroundColor": "#0000FF",
	    "top": 740,
	    "left": 50
	  },
	  "quitPlayText": {
	    "color": "#FFFFFF",
	    "fontSize": 60,
	    "textAlign": "center",
	    "fontWeight": "bold"
	  }
	}

/***/ },
/* 3 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){"use strict";

	module.exports = {
	    data: function () {return {
	        bgImgSrc: "https://13111211.github.io/weexCompetition/imgs/background/bg5.jpg"
	    }}
	};}
	/* generated by weex-loader */


/***/ }
/******/ ]);